[package]
name = "paging"
version = "0.1.0"
authors = ["Shardul Nalegave <nalegaveshardul40@gmail.com>"]
edition = "2018"

[dependencies]
vga = { path = "../vga" }
shared = { path = "../shared" }
x86_64 = "0.12.1"