[package]
name = "catalyst"
version = "0.1.0"
authors = ["Shardul Nalegave <nalegaveshardul40@gmail.com>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.9.8"