
[target.'cfg(target_os = "none")']
runner = "bootimage runner"

[build]
target = "x86_64-catalyst.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features=["compiler-builtins-mem"]

[package.metadata.bootimage]
test-args = ["-device", "isa-debug-exit,iobase=0xf4,iosize=0x04"]
test-success-exit-code = 33         # (0x10 << 1) | 1