[package]
name = "shared"
version = "0.1.0"
authors = ["Shardul Nalegave <nalegaveshardul40@gmail.com>"]
edition = "2018"

[dependencies]
vga = { path = "../vga" }
x86_64 = "0.12.1"
uart_16550 = "0.2.0"
spin = "0.5.2"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]